name: dnd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/spells.json
   - assets/weapons.json
   - assets/denna.json

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel/Cinzel-Black.ttf
    - family: Great Vibes
      fonts:
        - asset: assets/fonts/Great_Vibes/GreatVibes-Regular.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento/Sacramento-Regular.ttf
