name: dnd
description: D&D App Mockup

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  rxdart: ^0.23.1
  equatable: ^1.1.0
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.9
  firebase_storage: ^3.0.5
  flutter_screenutil: ^1.1.0
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/seeds/
   - assets/fonts/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel/Cinzel-Black.ttf
    - family: Great Vibes
      fonts:
        - asset: assets/fonts/Great_Vibes/GreatVibes-Regular.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento/Sacramento-Regular.ttf
